# Generated by Django 4.2.1 on 2023-05-22 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_quickpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickpin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quickpin',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
