# Generated by Django 4.2.1 on 2023-05-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_paymentcard_securenote_bankdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetail',
            new_name='BankDetails',
        ),
    ]
