# Generated by Django 4.2.1 on 2023-05-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_bankdetails_ac_no_last_four_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='expiration_month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='expiration_year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
