# Generated by Django 4.2.1 on 2023-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_paymentcard_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='expiration_year',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
