# Generated by Django 4.2.1 on 2023-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_paymentcard_expiration_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcard',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='expiration_year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
