# Generated by Django 4.2.1 on 2023-05-30 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_paymentcard_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCards',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=255)),
                ('card_no_last_four', models.CharField(blank=True, max_length=50, null=True)),
                ('cvv', models.CharField(max_length=255)),
                ('expiration_month', models.CharField(max_length=255, null=True)),
                ('expiration_year', models.CharField(max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
